from enum import Enum

class APLRace(Enum):
  ORC = "orc"
  UNDEAD = "undead"
  TAUREN = "tauren"
  TROLL = "troll"
  BLOOD_ELF = "blood_elf"
  GOBLIN = "goblin"
  PANDAREN = "pandaren"
  HUMAN = "human"
  DWARF = "dwarf"
  NIGHT_ELF = "night_elf"
  GNOME = "gnome"
  DRAENEI = "draenei"
  WORGEN = "worgen"
  NIGHTBORNE = "nightborne"
  HIGHMOUNTAIN_TAUREN = "highmountain_tauren"
  MAGHAR_ORC = "maghar_orc"
  ZANDALARI_TROLL = "zandalari_troll"
  VULPERA = "vulpera"
  VOID_ELF = "void_elf"
  LIGHTFORGED_DRAENEI = "lightforged_draenei"
  DARK_IRON_DWARF = "dark_iron_dwarf"
  KUL_TIRAN = "kul_tiran"
  MECHAGNOME = "mechagnome"
